// Generated by https://quicktype.io

namespace QuickType;

using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public partial class AzureWorkItemNotification
{
    [JsonProperty("subscriptionId")]
    public Guid SubscriptionId { get; set; }

    [JsonProperty("notificationId")]
    public long NotificationId { get; set; }

    [JsonProperty("id")]
    public Guid Id { get; set; }

    [JsonProperty("eventType")]
    public string EventType { get; set; }

    [JsonProperty("publisherId")]
    public string PublisherId { get; set; }

    [JsonProperty("message")]
    public Message Message { get; set; }

    [JsonProperty("detailedMessage")]
    public Message DetailedMessage { get; set; }

    [JsonProperty("resource")]
    public Resource Resource { get; set; }

    [JsonProperty("resourceVersion")]
    public string ResourceVersion { get; set; }

    [JsonProperty("resourceContainers")]
    public ResourceContainers ResourceContainers { get; set; }

    [JsonProperty("createdDate")]
    public DateTimeOffset CreatedDate { get; set; }
}

public partial class Message
{
    [JsonProperty("text")]
    public string Text { get; set; }

    [JsonProperty("html")]
    public string Html { get; set; }

    [JsonProperty("markdown")]
    public string Markdown { get; set; }
}

public partial class Resource
{
    [JsonProperty("id")]
    public long Id { get; set; }

    [JsonProperty("workItemId")]
    public long WorkItemId { get; set; }

    [JsonProperty("rev")]
    public long Rev { get; set; }

    [JsonProperty("revisedBy")]
    public EdBy RevisedBy { get; set; }

    [JsonProperty("revisedDate")]
    public DateTimeOffset RevisedDate { get; set; }

    [JsonProperty("fields")]
    public Dictionary<string, Field> Fields { get; set; }

    [JsonProperty("_links")]
    public ResourceLinks Links { get; set; }

    [JsonProperty("url")]
    public Uri Url { get; set; }

    [JsonProperty("revision")]
    public Revision Revision { get; set; }
}

public partial class Field
{
    [JsonProperty("oldValue")]
    public string OldValue { get; set; }

    [JsonProperty("newValue")]
    public string NewValue { get; set; }
}

public partial class ResourceLinks
{
    [JsonProperty("self")]
    public Parent Self { get; set; }

    [JsonProperty("parent")]
    public Parent Parent { get; set; }

    [JsonProperty("workItemUpdates")]
    public Parent WorkItemUpdates { get; set; }
}

public partial class Parent
{
    [JsonProperty("href")]
    public Uri Href { get; set; }
}

public partial class EdBy
{
    [JsonProperty("id")]
    public Guid Id { get; set; }

    [JsonProperty("displayName")]
    public string DisplayName { get; set; }

    [JsonProperty("url")]
    public Uri Url { get; set; }

    [JsonProperty("_links")]
    public RevisedByLinks Links { get; set; }

    [JsonProperty("uniqueName")]
    public string UniqueName { get; set; }

    [JsonProperty("imageUrl")]
    public Uri ImageUrl { get; set; }

    [JsonProperty("descriptor")]
    public string Descriptor { get; set; }
}

public partial class RevisedByLinks
{
    [JsonProperty("avatar")]
    public Parent Avatar { get; set; }
}

public partial class Revision
{
    [JsonProperty("id")]
    public long Id { get; set; }

    [JsonProperty("rev")]
    public long Rev { get; set; }

    [JsonProperty("fields")]
    public Fields Fields { get; set; }

    [JsonProperty("url")]
    public Uri Url { get; set; }
}

public partial class Fields
{
    [JsonProperty("System.AreaPath")]
    public string SystemAreaPath { get; set; }

    [JsonProperty("System.TeamProject")]
    public string SystemTeamProject { get; set; }

    [JsonProperty("System.IterationPath")]
    public string SystemIterationPath { get; set; }

    [JsonProperty("System.WorkItemType")]
    public string SystemWorkItemType { get; set; }

    [JsonProperty("System.State")]
    public string SystemState { get; set; }

    [JsonProperty("System.Reason")]
    public string SystemReason { get; set; }

    [JsonProperty("System.CreatedDate")]
    public DateTimeOffset SystemCreatedDate { get; set; }

    [JsonProperty("System.CreatedBy")]
    public EdBy SystemCreatedBy { get; set; }

    [JsonProperty("System.ChangedDate")]
    public DateTimeOffset SystemChangedDate { get; set; }

    [JsonProperty("System.ChangedBy")]
    public EdBy SystemChangedBy { get; set; }

    [JsonProperty("System.Title")]
    public string SystemTitle { get; set; }

    [JsonProperty("Microsoft.VSTS.Common.Severity")]
    public string MicrosoftVstsCommonSeverity { get; set; }

    [JsonProperty("WEF_EB329F44FE5F4A94ACB1DA153FDF38BA_Kanban.Column")]
    public string WefEb329F44Fe5F4A94Acb1Da153Fdf38BaKanbanColumn { get; set; }
}

public partial class ResourceContainers
{
    [JsonProperty("collection")]
    public Account Collection { get; set; }

    [JsonProperty("account")]
    public Account Account { get; set; }

    [JsonProperty("project")]
    public Account Project { get; set; }
}

public partial class Account
{
    [JsonProperty("id")]
    public Guid Id { get; set; }
}

public partial class AzureWorkItemNotification
{
    public static AzureWorkItemNotification FromJson(string json) => JsonConvert.DeserializeObject<AzureWorkItemNotification>(json, QuickType.Converter.Settings);
}

public static class Serialize
{
    public static string ToJson(this AzureWorkItemNotification self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
}

internal static class Converter
{
    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    {
        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
        DateParseHandling = DateParseHandling.None,
        Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
    };
}
