// Generated by https://quicktype.io

namespace QuickType;

using System;
using Newtonsoft.Json;

public class DiscordWebhookModel
{
    [JsonProperty("username")]
    public string? Username { get; set; }

    [JsonProperty("avatar_url")]
    public Uri? AvatarUrl { get; set; }

    [JsonProperty("embeds")]
    public IEnumerable<Embed> Embeds { get; set; } = new List<Embed>();
}

public partial class Embed
{
    [JsonProperty("title")]
    public string? Title { get; set; }

    [JsonProperty("description")]
    public string? Description { get; set; }
}