// Generated by https://quicktype.io

namespace QuickType;

using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public partial class DiscordWebhookModel
{
    [JsonProperty("username")]
    public string Username { get; set; }

    [JsonProperty("avatar_url")]
    public Uri AvatarUrl { get; set; }

    [JsonProperty("embeds")]
    public Embed[] Embeds { get; set; }
}

public partial class Embed
{
    [JsonProperty("title")]
    public string Title { get; set; }

    [JsonProperty("description")]
    public string Description { get; set; }
}

public partial class DiscordWebhookModel
{
    public static DiscordWebhookModel FromJson(string json) => JsonConvert.DeserializeObject<DiscordWebhookModel>(json, QuickType.ConverterDiscordWebhookModel.Settings);
}

internal static class ConverterDiscordWebhookModel
{
    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    {
        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
        DateParseHandling = DateParseHandling.None,
        Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
    };
}

